zoom in: edit.zoom_in()
zoom out: edit.zoom_out()
zoom reset: edit.zoom_reset()
scroll up: edit.page_up()
scroll down: edit.page_down()
copy that: edit.copy()
cut that: edit.cut()
(pace | paste) that: edit.paste()
paste enter:
    edit.paste()
    key(enter)
nope: edit.undo()
redo: edit.redo()
paste match: edit.paste_match_style()
save that: edit.save()
save all: edit.save_all()
(pad | padding): user.insert_between(" ", " ")
slap: edit.line_insert_down()
